# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db27f2bf7275e0427721e978111623acc3a6c45ca179c13bd50b3e9562859edda401d9c4d6109f8d25ded1e0bcff6a33b335778aac8b753fc68077e6cada16c

test:
  secret_key_base: 53db983faf4e3ee10692e813b3db0d688af27a2f782ad24eeb3592dcb4b2ba3f20a9ac266280a16cb98fda6d6d4b1fb7bcc55c1dfa271a5a635e54190ea64f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
